=== luisfrancisco/18xx-maker/src/schemas/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://18xx-maker.com/schemas/config.schema.json",
  "definitions": {
    "font": {
      "type": "object",
      "properties": {
        "size": {
          "type": "string"
        },
        "weight": {
          "type": "string",
          "enum": ["normal", "bold"]
        },
        "family": {
          "type": "string"
        }
      },
      "additionalProperties": {
        "$ref": "#/definitions/font"
      }
    },
    "dimension": {
      "type": "integer",
      "minimum": 1
    },
    "dimensions": {
      "type": "object",
      "properties": {
        "width": {
          "$ref": "#/definitions/dimension"
        },
        "height": {
          "$ref": "#/definitions/dimension"
        }
      },
      "required": ["width", "height"]
    },
    "margins": {
      "$ref": "#/definitions/dimension"
    },
    "pins": {
      "type": "object",
      "properties": {
        "innerRadius": {
          "type": "number",
          "minimum": 0
        },
        "outerRadius": {
          "type": "number",
          "minimum": 0
        },
        "y": {
          "type": "number",
          "minimum": 0
        },
        "x1": {
          "type": "number",
          "minimum": 0
        },
        "x2": {
          "type": "number",
          "minimum": 0
        }
      },
      "required": ["innerRadius", "outerRadius", "y", "x1", "x2"],
      "additionalProperties": false
    }
  },
  "type": "object",
  "properties": {
    "theme": {
      "type": "string"
    },
    "companiesTheme": {
      "type": "string"
    },
    "paper": {
      "allOf": [
        {
          "$ref": "#/definitions/dimensions"
        },
        {
          "type": "object",
          "properties": {
            "margins": {
              "$ref": "#/definitions/margins"
            }
          },
          "required": ["margins"]
        }
      ]
    },
    "currency": {
      "type": "object",
      "properties": {
        "bank": {
          "type": "boolean"
        },
        "border": {
          "type": "boolean"
        },
        "capital": {
          "type": "boolean"
        },
        "market": {
          "type": "boolean"
        },
        "offboard": {
          "type": "boolean"
        },
        "par": {
          "type": "boolean"
        },
        "private": {
          "type": "boolean"
        },
        "revenue": {
          "type": "boolean"
        },
        "share": {
          "type": "boolean"
        },
        "terrain": {
          "type": "boolean"
        },
        "token": {
          "type": "boolean"
        },
        "train": {
          "type": "boolean"
        },
        "treasury": {
          "type": "boolean"
        },
        "value": {
          "type": "boolean"
        }
      },
      "required": [
        "bank",
        "border",
        "capital",
        "market",
        "offboard",
        "par",
        "private",
        "revenue",
        "terrain",
        "token",
        "train",
        "value"
      ],
      "additionalProperties": false
    },
    "stock": {
      "type": "object",
      "properties": {
        "cell": {
          "$ref": "#/definitions/dimensions"
        },
        "value": {
          "type": "string",
          "enum": ["top", "bottom"]
        },
        "arrows": {
          "type": "string",
          "enum": ["top", "middle", "bottom"]
        },
        "column": {
          "type": "number"
        },
        "diag": {
          "type": "number"
        },
        "par": {
          "type": "number"
        },
        "display": {
          "type": "object",
          "properties": {
            "legend": {
              "type": "boolean"
            },
            "par": {
              "type": "boolean"
            },
            "roundTracker": {
              "type": "boolean"
            }
          },
          "required": ["legend", "par", "roundTracker"],
          "additionalProperties": false
        }
      },
      "required": ["cell", "value", "column", "diag", "par"],
      "additionalProperties": false
    },
    "cutlines": {
      "type": "number",
      "minimum": 0
    },
    "cutlinesOffset": {
      "type": "number",
      "minimum": 0
    },
    "bleed": {
      "type": "number",
      "minimum": 0
    },
    "margin": {
      "type": "number",
      "minimum": 0
    },
    "export": {
      "type": "object",
      "properties": {
        "allLayouts": {
          "type": "boolean"
        },
        "bleed": {
          "type": "boolean"
        },
        "cropMarks": {
          "type": "boolean"
        },
        "dieline": {
          "type": "boolean"
        },
        "bleedSize": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "cards": {
      "type": "object",
      "properties": {
        "shareStyle": {
          "type": "string",
          "enum": ["center", "left", "gmt"]
        },
        "layout": {
          "type": "string",
          "enum": ["free", "miniEuroDie", "dtgDie"]
        },
        "width": {
          "type": "number",
          "minimum": 1
        },
        "height": {
          "type": "number",
          "minimum": 1
        },
        "cutlines": {
          "type": "number",
          "minimum": 0
        },
        "bleed": {
          "type": "number",
          "minimum": 0
        },
        "dtgPadding": {
          "type": "number",
          "minimum": 0
        },
        "border": {
          "type": "number",
          "minimum": 0
        },
        "blackBand": {
          "type": "boolean"
        },
        "pins": {
          "$ref": "#/definitions/pins"
        }
      },
      "required": [
        "shareStyle",
        "layout",
        "width",
        "height",
        "cutlines",
        "bleed",
        "dtgPadding",
        "blackBand",
        "pins"
      ],
      "additionalProperties": false
    },
    "privates": {
      "type": "object",
      "properties": {
        "style": {
          "type": "string",
          "enum": ["small", "big"]
        }
      },
      "additionalProperties": false,
      "required": ["style"]
    },
    "trains": {
      "type": "object",
      "properties": {
        "style": {
          "type": "string",
          "enum": ["color", "number"]
        },
        "images": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "required": ["style", "images"]
    },
    "charters": {
      "type": "object",
      "properties": {
        "style": {
          "type": "string",
          "enum": ["carth", "color"]
        },
        "layout": {
          "type": "string",
          "enum": ["free", "3x1", "3x2", "3x1minors"]
        },
        "cutlines": {
          "type": "number",
          "minimum": 0
        },
        "bleed": {
          "type": "number",
          "minimum": 0
        },
        "border": {
          "type": "number",
          "minimum": 0
        },
        "halfWidth": {
          "type": "boolean"
        },
        "smallerMinors": {
          "type": "boolean"
        },
        "blackBand": {
          "type": "boolean"
        },
        "showPhaseChart": {
          "type": "boolean"
        },
        "showTurnOrder": {
          "type": "boolean"
        },
        "pins": {
          "$ref": "#/definitions/pins"
        }
      },
      "required": ["style", "halfWidth", "cutlines", "border", "blackBand"],
      "additionalProperties": false
    },
    "tokens": {
      "type": "object",
      "properties": {
        "layout": {
          "type": "string",
          "enum": ["free", "gsp"]
        },
        "reverseMarketTokens": {
          "type": "string",
          "enum": ["none", "one", "all"]
        },
        "marketTokenSize": {
          "type": "number",
          "minimum": 1
        },
        "stationTokenSize": {
          "type": "number",
          "minimum": 1
        },
        "generalTokenSize": {
          "type": "number",
          "minimum": 1
        },
        "bleed": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "required": ["layout", "marketTokenSize", "stationTokenSize", "bleed"]
    },
    "coords": {
      "type": "string",
      "enum": ["outside", "inside", "edge", "none"]
    },
    "tiles": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "enum": ["right", "left", "none"]
        },
        "colorblind": {
          "type": "boolean"
        },
        "layout": {
          "type": "string",
          "enum": ["offset", "individual", "die", "smallDie"]
        },
        "width": {
          "type": "number",
          "exclusiveMinimum": 0
        },
        "mapWidth": {
          "type": "number",
          "exclusiveMinimum": 0
        },
        "gaps": {
          "type": "boolean"
        },
        "pins": {
          "$ref": "#/definitions/pins"
        },
        "idOffset": {
          "type": "number",
          "minimum": 0
        }
      },
      "required": ["layout", "width", "mapWidth", "gaps"],
      "additionalProperties": false
    },
    "companySvgLogos": {
      "type": "string",
      "enum": ["none", "original", "match", "main"]
    },
    "overrideCompanies": {
      "type": "string",
      "enum": [
        "none",
        "languages",
        "lotr",
        "dev",
        "webdev",
        "owl",
        "1830",
        "1830-Mayfair"
      ]
    },
    "overrideSelection": {
      "type": "array",
      "items": {
        "type": "integer",
        "minimum": 0
      }
    },
    "maps": {
      "type": "object",
      "required": ["market", "players", "roundTracker"],
      "additionalProperties": false,
      "properties": {
        "market": {
          "type": "boolean"
        },
        "players": {
          "type": "boolean"
        },
        "roundTracker": {
          "type": "boolean"
        }
      }
    },
    "plainMapCompanies": {
      "type": "boolean"
    },
    "straightCityNames": {
      "type": "boolean"
    },
    "font": {
      "$ref": "#/definitions/font"
    }
  },
  "required": [
    "bleed",
    "companiesTheme",
    "companySvgLogos",
    "coords",
    "cutlines",
    "cutlinesOffset",
    "font",
    "margin",
    "overrideCompanies",
    "overrideSelection",
    "paper",
    "plainMapCompanies",
    "stock",
    "theme",
    "tokens"
  ],
  "additionalProperties": false
}

=== luisfrancisco/18xx-maker/src/defaults.json
{
  "coords": "outside",
  "font": {
    "family": "display",
    "size": "0.15in",
    "weight": "bold"
  },
  "cutlines": 25,
  "cutlinesOffset": 0,
  "bleed": 12.5,
  "margin": 25,
  "paper": {
    "width": 850,
    "height": 1100,
    "margins": 25
  },
  "currency": {
    "bank": true,
    "border": true,
    "capital": true,
    "market": false,
    "offboard": false,
    "par": false,
    "private": true,
    "revenue": false,
    "share": true,
    "terrain": true,
    "token": true,
    "train": true,
    "treasury": true,
    "value": false
  },
  "companySvgLogos": "main",
  "overrideCompanies": "none",
  "overrideSelection": [],
  "maps": {
    "players": true,
    "roundTracker": true,
    "market": true
  },
  "plainMapCompanies": false,
  "straightCityNames": false,
  "theme": "gmt",
  "companiesTheme": "rob",
  "export": {
    "allLayouts": false,
    "bleed": true,
    "cropMarks": true,
    "dieline": false,
    "bleedSize": 12.5
  },
  "charters": {
    "style": "color",
    "layout": "free",
    "cutlines": 25,
    "bleed": 12.5,
    "halfWidth": false,
    "smallerMinors": true,
    "border": 0,
    "blackBand": false,
    "showPhaseChart": true,
    "showTurnOrder": true,
    "pins": {
      "innerRadius": 6.25,
      "outerRadius": 12.5,
      "y": 25,
      "x1": 75,
      "x2": 675
    }
  },
  "cards": {
    "shareStyle": "gmt",
    "layout": "miniEuroDie",
    "width": 265.748,
    "height": 173.228,
    "cutlines": 25,
    "bleed": 12.5,
    "dtgPadding": 0,
    "border": 0,
    "blackBand": false,
    "pins": {
      "innerRadius": 6.25,
      "outerRadius": 12.5,
      "y": 25,
      "x1": 100,
      "x2": 700
    }
  },
  "tokens": {
    "layout": "free",
    "marketTokenSize": 50,
    "stationTokenSize": 37.5,
    "generalTokenSize": 50,
    "bleed": true,
    "reverseMarketTokens": "all"
  },
  "privates": {
    "style": "small"
  },
  "trains": {
    "style": "color",
    "images": false
  },
  "tiles": {
    "id": "right",
    "colorblind": false,
    "layout": "die",
    "width": 150,
    "mapWidth": 150,
    "gaps": true,
    "pins": {
      "innerRadius": 6.25,
      "outerRadius": 12.5,
      "y": 25,
      "x1": 100,
      "x2": 700
    },
    "idOffset": 0
  },
  "stock": {
    "cell": {
      "width": 70,
      "height": 85
    },
    "value": "top",
    "arrows": "bottom",
    "column": 4,
    "diag": 2,
    "par": 4,
    "display": {
      "legend": true,
      "par": true,
      "roundTracker": true
    }
  }
}
